### PR TITLE
Milestone 3: Feature/styling

### PR DESCRIPTION
**Pull request by alvp01**
#In this milestone:

- Now you should improve the look and feel of the application, adding the styles of your choice.
- Please keep the general layout of the wireframe, this is the only mandatory requirement.

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hello @alvp01 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Linter is correct 
- Descriptive pr summary and headline 
- Great design 

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄


 ## Required Changes ♻️

- [x] Kindly fix the broken issues page link for complete professional README file. 
- [x] Please make sure you provide a valid live demo link in the README file. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alvp01** [comment]
> Hello @alvp01 smiley,
> 
> Great work and effort you put into this project so far.
> ## Highlights rocket
> 
> There are some excellent points that you have made perfectly. Keep up! muscle
> 
>     * Linter is correct
> 
>     * Descriptive pr summary and headline
> 
>     * Great design
> 
> 
> However, there is always room for improvement.
> 
> > Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. smile
> 
> ## Required Changes recycle
> 
>     * [x]  Kindly fix the broken issues page link for complete professional README file.
> 
>     * [x]  Please make sure you provide a valid live demo link in the README file.
> 
> 
> ## Optional suggestions
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> N/A
> 
> Cheers and Happy coding!clapman_technologistcomputer
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Sorry about the broken links. Fixed them right away

**Review by DeliceLydia — APPROVED** [review]
## Congratulations🎉 🎉 

### Hi @alvp01 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alvp01** [comment]
> ## Congratulationstada tada
> ### Hi @alvp01 ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
> Congratulations! tada
> ### Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you for your time and work! Happy weekend.

**Pull request merged**
